/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sorteio;

import java.util.List;

/**
 *
 * @author 182400306
 */
public class Palpites extends javax.swing.JDialog {

    /**
     * Creates new form Palpites
     */
    public Palpites(java.awt.Frame parent, boolean modal, Sorteio sorteio) {
        super(parent, modal);
        initComponents();
        mostrarPalpites(sorteio);
    }

    private void mostrarPalpites(Sorteio sorteio) {
        List<Pessoa> participantes = sorteio.getPessoas();
        StringBuilder sb = new StringBuilder();
        for (Pessoa p : participantes) {
            sb.append("Participante: ").append(p.getNome()).append("\n");
            sb.append("Palpite: ").append(p.getNumeroEscolhido()).append("\n");
            sb.append("\n");
        }
        txtPalpites.setText(sb.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTituloPopupPalpites = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPalpites = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelTituloPopupPalpites.setText("Palpites");

        txtPalpites.setColumns(20);
        txtPalpites.setRows(5);
        jScrollPane1.setViewportView(txtPalpites);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(labelTituloPopupPalpites)
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTituloPopupPalpites)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTituloPopupPalpites;
    private javax.swing.JTextArea txtPalpites;
    // End of variables declaration//GEN-END:variables

}
