/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sorteio;

/**
 *
 * @author 182400306
 */
public class Palpites extends javax.swing.JDialog {

    /** Creates new form Palpites */
    public Palpites(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        palpite1 = new javax.swing.JLabel();
        palpite2 = new javax.swing.JLabel();
        labelTituloPopupPalpites = new javax.swing.JLabel();
        palpite3 = new javax.swing.JLabel();
        palpite4 = new javax.swing.JLabel();
        palpite5 = new javax.swing.JLabel();
        palpite6 = new javax.swing.JLabel();
        palpite7 = new javax.swing.JLabel();
        palpite8 = new javax.swing.JLabel();
        palpite9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        palpite1.setText("1 - Nome - Palpite");

        palpite2.setText("2 - Nome - Palpite");

        labelTituloPopupPalpites.setText("Palpites");

        palpite3.setText("3 - Nome - Palpite");

        palpite4.setText("4 - Nome - Palpite");

        palpite5.setText("5");

        palpite6.setText("6");

        palpite7.setText("7");

        palpite8.setText("8");

        palpite9.setText("9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(palpite2)
                            .addComponent(palpite1)
                            .addComponent(palpite3)
                            .addComponent(palpite4)
                            .addComponent(palpite5)
                            .addComponent(palpite6)
                            .addComponent(palpite7)
                            .addComponent(palpite8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(labelTituloPopupPalpites))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(palpite9)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTituloPopupPalpites)
                .addGap(16, 16, 16)
                .addComponent(palpite1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(palpite2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(palpite3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(palpite4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(palpite5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(palpite6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(palpite7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(palpite8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(palpite9)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelTituloPopupPalpites;
    private javax.swing.JLabel palpite1;
    private javax.swing.JLabel palpite2;
    private javax.swing.JLabel palpite3;
    private javax.swing.JLabel palpite4;
    private javax.swing.JLabel palpite5;
    private javax.swing.JLabel palpite6;
    private javax.swing.JLabel palpite7;
    private javax.swing.JLabel palpite8;
    private javax.swing.JLabel palpite9;
    // End of variables declaration//GEN-END:variables

}
