/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sorteio;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 182400306
 */
public class PrevPalpites extends javax.swing.JDialog {

    /**
     * Creates new form Palpites
     */
    public PrevPalpites(java.awt.Frame parent, boolean modal, Sorteio sorteio, Sorteado sorteados) {
        super(parent, modal);
        initComponents();
        mostrarPalpites(sorteados, sorteio);
    }

    private void mostrarPalpites(Sorteado sorteados, Sorteio sorteio) {
        if (sorteados != null) {
            List<Pessoa> vencedores = sorteados.getVencedores();
            List<Integer> numerosSorteados = sorteados.getNumerosSorteados();
            List<Integer> diferencas = sorteados.getDiferencas();

            if (vencedores != null && numerosSorteados != null && diferencas != null) {
                DefaultTableModel model = (DefaultTableModel) tbPrevSorteio.getModel();
                model.setRowCount(0); // Limpa qualquer linha existente

                for (int i = 0; i < vencedores.size(); i++) {
                    Pessoa p = vencedores.get(i);
                    model.addRow(new Object[]{
                        p.getNome(),
                        p.getNumeroEscolhido(),
                        numerosSorteados.get(i),
                        diferencas.get(i)
                    });
                }
            } else {
                JOptionPane.showMessageDialog(this, "Nenhum vencedor encontrado.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Nenhum sorteio foi fornecido.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTituloPopupPalpites = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPrevSorteio = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelTituloPopupPalpites.setText("Palpites");

        tbPrevSorteio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Nome", "Palpite", "Número Escolhido", "Diferença"
            }
        ));
        jScrollPane2.setViewportView(tbPrevSorteio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(labelTituloPopupPalpites)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTituloPopupPalpites)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelTituloPopupPalpites;
    private javax.swing.JTable tbPrevSorteio;
    // End of variables declaration//GEN-END:variables

}
