/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sorteio;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author 182400306
 */
public class Resultados extends javax.swing.JDialog {

    /**
     * Creates new form Resultados
     */
    public Resultados(java.awt.Frame parent, boolean modal, Sorteio sorteio, Sorteado sorteados) {
        super(parent, modal);
        initComponents();
        novoSorteio(sorteio, sorteados);
    }

    private void novoSorteio(Sorteio sorteio, Sorteado sorteados) {
        List<Pessoa> participantes = sorteio.getPessoas();
        Pessoa vencedor = sorteio.realizarSorteio();
        sorteados.addVencedor(vencedor);
        sorteados.addNumeroSorteado(sorteio.getNumeroSorteado());
        sorteados.addDiferenca(sorteio.getDif());
        labelNumSorteado.setText(String.valueOf(sorteio.getNumeroSorteado()));

        StringBuilder sb = new StringBuilder();
        for (Pessoa p : participantes) {
            int diferenca = Math.abs(p.getNumeroEscolhido() - sorteio.getNumeroSorteado());
            sb.append("Participante: ").append(p.getNome()).append("\n");
            sb.append("Palpite: ").append(p.getNumeroEscolhido()).append("\n");
            sb.append("Diferença: ").append(diferenca).append("\n\n");
        }

        txtResultados.setText(sb.toString());
        labelVencedor.setText("Vencedor: " + vencedor.getNome() + " - Palpite: " + vencedor.getNumeroEscolhido());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTituloResultados = new javax.swing.JLabel();
        labelTitNumSorteado = new javax.swing.JLabel();
        labelVencedor = new javax.swing.JLabel();
        labelNumSorteado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultados = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelTituloResultados.setText("Resultados");

        labelTitNumSorteado.setText("Numero Sorteado:");

        txtResultados.setColumns(20);
        txtResultados.setRows(5);
        jScrollPane1.setViewportView(txtResultados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelVencedor)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTituloResultados)
                        .addGap(30, 30, 30)
                        .addComponent(labelTitNumSorteado)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNumSorteado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTituloResultados)
                    .addComponent(labelTitNumSorteado)
                    .addComponent(labelNumSorteado))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(labelVencedor)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelNumSorteado;
    private javax.swing.JLabel labelTitNumSorteado;
    private javax.swing.JLabel labelTituloResultados;
    private javax.swing.JLabel labelVencedor;
    private javax.swing.JTextArea txtResultados;
    // End of variables declaration//GEN-END:variables
}
